test: migrate from mocha and chai to jest
nmshd/cns-transport pull request #68
Opened 2024-01-12 16:09 UTC by sebbi08

2024-01-15 09:07 UTC, jkoenig134 requested changes

2024-01-15 09:07 UTC, jkoenig134 commented on test/performance/Dockerfile
> +ENTRYPOINT npx jest --testPathIgnorePatterns="[]" --testPathPattern="test/performance" --listTests
```suggestion
ENTRYPOINT npx jest --testPathIgnorePatterns="[]" --testPathPattern="test/performance"
```

2024-01-15 09:07 UTC, jkoenig134 commented on package.json
> +            "/node_modules/"
is this necessary?

2024-01-15 09:07 UTC, jkoenig134 commented on test/performance/Dockerfile
> +ENTRYPOINT npx jest --testPathIgnorePatterns="[]" --testPathPattern="test/performance" --listTests
this will exit without running the tests

2024-01-15 09:07 UTC, jkoenig134 commented on test/testHelpers/AppDeviceTest.ts
I think we don't need this file anymore

2024-01-15 09:07 UTC, jkoenig134 commented on test/testHelpers/DeviceTestParameters.ts
is this still used?

2024-01-15 09:07 UTC, jkoenig134 commented on test/testHelpers/FakeDbCollectionProvider.ts
why is this removed? unused?

2024-01-15 09:07 UTC, jkoenig134 commented on test/testHelpers/LogInterceptor.ts
unused?

2024-01-15 09:07 UTC, jkoenig134 commented on test/testHelpers/MockDatabaseCollection.ts
unused?

2024-01-15 15:22 UTC, sebbi08 commented on test/modules/sync/BackboneConcurrency.test.ts
> +        // REVISIT is this ok ? multiple occurences in the sync tests
the problem was i forgot to remove it :)

2024-01-15 15:45 UTC, sebbi08 commented on package.json
> +            "/node_modules/"
it is the default and is overwritten when specified so i readded it in the end no test where found in node modules but better save than sorry

2024-01-15 15:46 UTC, jkoenig134 commented on package.json
> +            "/node_modules/"
ok, I thought this simply get added.

2024-01-15 15:52 UTC, sebbi08 commented on test/testHelpers/AppDeviceTest.ts
it is used in the DeviceOnboarding and DeviceDeletion test should i remove it and move the methods to the TestUtil ?

2024-01-15 15:53 UTC, sebbi08 commented on test/testHelpers/FakeDbCollectionProvider.ts
yes

2024-01-15 15:53 UTC, sebbi08 commented on test/testHelpers/LogInterceptor.ts
y

2024-01-15 15:53 UTC, sebbi08 commented on test/testHelpers/MockDatabaseCollection.ts
y

2024-01-15 15:55 UTC, jkoenig134 commented on test/testHelpers/AppDeviceTest.ts
no, I was confused. It can stay

2024-01-16 07:26 UTC, jkoenig134 commented on test/modules/sync/SyncController.callback.test.ts
>      afterEach(async function () {
afterAll, not afterEach

2024-01-16 07:56 UTC, jkoenig134 submitted a review, later dismissed

2024-01-16 10:02 UTC, jkoenig134 approved these changes

2024-01-16 10:07 UTC, merged