Feature/JSSNMSHDD-2572 implement datawallet version
nmshd/cns-transport pull request #9
Opened 2021-10-06 13:16 UTC by jkoenig134

2021-11-02 08:01 UTC, tnotheis commented on src/modules/sync/SyncController.ts
> +            const outdatedErrorCode = "error.platform.validation.datawallet.versionOutdated"
2 Sachen:

1. Ich hab den Error Code bei mir `error.platform.validation.datawallet.insufficientSupportedDatawalletVersion` genannt. 
2. Der Fehler kann bei `POST /Datawallet/Modifications`, `GET /Datawallet/Modifications` und `POST /SyncRuns` auftreten. Stelle sicher, dass er überall abgefangen wird.

2021-11-02 08:08 UTC, jkoenig134 commented on src/modules/sync/backbone/StartSyncRun.ts
> +    lockDuration?: number
Das hatte ich aus der Doku. duration finde ich auch besser.

2021-11-02 08:28 UTC, jkoenig134 commented on src/modules/sync/SyncController.ts
> +            const outdatedErrorCode = "error.platform.validation.datawallet.versionOutdated"
1. Code ist angepasst
2. Das ganze try..catch geht um den gesamten datawalletSync herum, sollte also alles abgedeckt sein.

2021-11-02 12:40 UTC, tnotheis commented on src/modules/sync/SyncController.ts
> +            const outdatedErrorCode = "error.platform.validation.datawallet.versionOutdated"
Und was ist mit den Aufrufen in syncEverything? Oder in setInitialSyncRun?

2021-11-02 16:16 UTC, tnotheis commented on src/modules/sync/SyncController.ts
> +                this.config.supportedDatawalletVersion
Mir ist gerade beim Review meines eigenen Bacbkone-PRs aufgefallen, dass ich sowieso keine Möglichkeit mehr biete, die Datawallet Version pro Modification mitzugeben. Stattdessen setze ich die Version implizit auf die Version, die die Datawallet zum Zeitpunkt des Pushs auf dem Backbone hat.

2021-11-03 06:23 UTC, jkoenig134 commented on src/modules/sync/SyncController.ts
> +                this.config.supportedDatawalletVersion
Hm, das ist aber nicht so gut.. Du kannst das ja nicht wissen mit welcher Datawalletversion die Modification erzeugt wurde.

2021-11-03 06:27 UTC, jkoenig134 commented on src/modules/sync/SyncController.ts
> +                this.config.supportedDatawalletVersion
> und deshalb noch 1er Modifications erzeugt werden
Also ich glaube, dass das nicht möglich ist. Das Upgrade sorgt ja nur dafür alte Daten auf ne neue Version zu heben, neue Daten werden immer mit der neusten Version erzeugt.

2021-11-04 14:56 UTC, tnotheis requested changes

2021-11-04 14:56 UTC, tnotheis commented on src/modules/sync/backbone/FinalizeSyncRun.ts
> +    datawalletModifications: {
Warum benutzt du hier nicht `CreateDatawalletModificationsRequestItem`?

2021-11-04 14:56 UTC, tnotheis commented on src/modules/sync/backbone/StartSyncRun.ts
> +    type?: SyncRunType
Das ist ein Pflichtfeld

2021-11-04 14:56 UTC, tnotheis commented on src/modules/sync/migrations/IdentityMigrations.ts
> +        return Promise.resolve()
Vielleicht noch einen kleinen Kommentar rein im Sinne von "no upgrade steps necessary for v1"

2021-11-04 14:56 UTC, tnotheis commented on test/core/backbone/Authentication.test.ts
> +                setAuthTokenToExpired(testAccount)
Was is das?

2021-11-04 14:56 UTC, tnotheis commented on test/modules/sync/builder/DatawalletModificationBuilder.ts
> +    private datawalletVersion = 0
Mach hier mal bitte ne 1. Sollte egal sein, aber 0 ist ja eigentlich keine valide Version. Haben wir ja nur aus Legacy Gründen

2021-11-04 14:56 UTC, tnotheis commented on test/Test.ts
> +    public static readonly currentEnvironment = BackboneEnvironment.Dev
Reminder: Auf Stage stellen vor dem Deployment

2021-11-04 14:56 UTC, tnotheis commented on src/modules/sync/SyncController.ts
> +    private readonly supportedDatawalletVersion: number
Würd ich gar nicht in ner extra Variablen speichern, sondern an den Verwendungsstellen direkt auf die config gehen

2021-11-04 14:56 UTC, tnotheis commented on src/modules/sync/SyncController.ts
> +        const syncRunWasStarted = await this.startExternalEventsSyncRun()
Tu mir mal einen Gefallen und lagere die Zeilen 88-97 in eine Methode `syncExternalEvents` aus.

2021-11-04 14:56 UTC, tnotheis commented on src/modules/sync/SyncController.ts
> +            throw TransportErrors.datawallet
Schreib hier mal einen Kommentar in Richtung "This means that the datawallet of the identity was upgraded by another device with a higher version. It is necesssary to update the current device."

2021-11-04 14:59 UTC, jkoenig134 commented on src/modules/devices/DeviceController.ts
> +        await this.parent.info.set("device", this.device.toJSON())
Ne, ich will abwärtskompatibel bleiben mit den libs. Tut ja nicht weh den toJSON zu haben ;)

2021-11-04 14:59 UTC, jkoenig134 commented on src/modules/relationshipTemplates/RelationshipTemplateController.ts
> +            identity: this.parent.identity.identity,
Das war vorher nen Fehler den typescript nicht erkannt hat

2021-11-04 15:00 UTC, jkoenig134 commented on src/modules/sync/backbone/FinalizeSyncRun.ts
> +    datawalletModifications: {
Weil das die response ist, die andere Felder hat

2021-11-04 15:02 UTC, jkoenig134 commented on test/core/backbone/Authentication.test.ts
> +                setAuthTokenToExpired(testAccount)
Hat nen Fehler geworfen. Scheint als würde ich nach dem init jetzt irgendwo etwas tun bei dem eine authentication läuft.

2021-11-04 15:03 UTC, jkoenig134 commented on src/modules/sync/SyncController.ts
> +    private readonly supportedDatawalletVersion: number
Hatte ich, wurde aber so oft genutzt. Aber von mir aus.

2021-11-17 13:07 UTC, tnotheis approved these changes

2021-11-18 09:48 UTC, jkoenig134 commented on test/modules/sync/SyncController.test.ts
> +                if (sender) await sender.close() // eslint-disable-line @typescript-eslint/no-unnecessary-condition
Das müsste man mal überall machen.. und vielleicht sender und recipient optional machen?

2021-11-18 11:50 UTC, jkoenig134 commented on test/testHelpers/FakeSyncClient.ts
> +import { GetDatawalletResponse } from "../../src/modules/sync/backbone/GetDatawallet"
weitere src imports

2021-11-24 07:53 UTC, tnotheis approved these changes

2021-11-24 08:11 UTC, merged